# Generated by Django 5.1.3 on 2024-12-10 08:10

import dev_pro.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPatientsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('procedure', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('patient_email', models.EmailField(max_length=254, unique=True)),
                ('referred', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='patientreports',
            name='patient_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_pro.patientsdetails'),
        ),
        migrations.CreateModel(
            name='NewPatientreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, upload_to=dev_pro.models.NewPatientreports.nameFile)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_pro.newpatientsdetails')),
            ],
        ),
    ]
