# Generated by Django 5.1.3 on 2024-12-10 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_pro', '0002_newpatientsdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpatientsdetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientsdetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
