# Generated by Django 5.1.4 on 2024-12-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_pro', '0003_newpatientsdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatientreports',
            name='patient_details_id',
            field=models.CharField(max_length=100),
        ),
    ]
