# Generated by Django 5.1.4 on 2025-01-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_pro', '0004_alter_newpatientreports_patient_details_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_video_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.CharField(max_length=500)),
                ('report_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_pro.newpatientreports')),
            ],
        ),
        migrations.CreateModel(
            name='video_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.CharField(max_length=500)),
                ('report_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_pro.patientreports')),
            ],
        ),
    ]
