
"""
Django settings for dev project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path


from django.conf.global_settings import MEDIA_URL, STATIC_ROOT, CSRF_TRUSTED_ORIGINS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print('BASE_DIR',BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bbgd1o(&q-t0#-h^*)g6y@j9sy3#7e2=9hvx)c2)oe-*ledu*8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.gis'

    'rest_framework',
    'corsheaders',
    'dev_pro',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]





# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
"http://127.0.0.1:8000",
    "http://localhost:3000",  # Frontend address
    "http://localhost:8000",  # Frontend address
    "http://192.168.0.129",
    "http://192.168.29.74:3000",
    "http://192.168.29.44:3000",
    "http://192.168.29.251:8000",
    'http://192.168.29.133',
"http://192.168.29.74:3002",
    # "http://192.168.29.185",# Add other allowed origins if needed
]
CORS_ALLOW_CREDENTIALS=True

CORS_ALLOW_HEADERS=[
    "content-type",
    "Authorization",
    "X-CSRFToken",


]

X_FRAME_OPTIONS = 'ALLOWALL'


CSRF_TRUSTED_ORIGINS=["http://127.0.0.1:8000"]


ROOT_URLCONF = 'dev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'build')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Sunil2662',
        'HOST': 'ytdatabase.c98k4qo8soa0.ap-south-1.rds.amazonaws.com',
        'PORT': '5432',
    },
    'fallback': {
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'testdb',  # change it databasename
        # 'USER': 'postgres',  # change it database username
        # 'PASSWORD': '275603',  # change user database password
        # # 'HOST': '192.168.29.185',
        # 'HOST': 'localhost',
        # #  'HOST': '192.168.0.129',
        # 'PORT': '5432',
        'ENGINE': 'django.db.backends.sqlite3',  # Use the SQLite backend
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_ROUTERS = ['dev.database_router.DatabaseRouter']

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your email service provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pushparaj4522@gmail.com'
EMAIL_HOST_PASSWORD = 'xgia dpbc ieqx hunq'
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'build/static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,"media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from decouple import config  # Optional, for managing environment variables




AWS_ACCESS_KEY_ID = 'AKIAVRUVWVFCSQBD3LNO'
AWS_SECRET_ACCESS_KEY = '5M5idAAN0hBxp3tdkn3A8wYcjdaxcZ7ePFT1syHg'
AWS_STORAGE_BUCKET_NAME = 'samplebucketautomac2'
AWS_S3_REGION_NAME = 'ap-south-1' # Update as needed
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'






EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "neerajpynam@gmail.com"
EMAIL_HOST_PASSWORD = "tkekaspbkdfjanap"









#
# AWS_ACCESS_KEY_ID = config('AKIAVRUVWVFCSQBD3LNO')
# AWS_SECRET_ACCESS_KEY = config('5M5idAAN0hBxp3tdkn3A8wYcjdaxcZ7ePFT1syHg')
# AWS_STORAGE_BUCKET_NAME = config('samplebucketautomac2')
# AWS_S3_REGION_NAME = config('ap-south-1', default='ap-south-1')  # Update as needed
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# Media Files
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'



